name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        

    - name: Build WordPress
      run: |
        # Your build steps here, e.g., theme compilation

    - name: Deploy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.WORDHOST }}
        username: ${{ secrets.WORDUSER }}
        key: ${{ secrets.WORDKEY }}
        source: "."
        target: "/var/www/html/gittarget"


